name: bengaliallinone
description: A new Flutter project.

# +=+=+=+=+=+=+=+ Developed by Sujit Chanda +=+=+=+=+=+=+=+
#

version: 1.9.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.4
  eva_icons_flutter: ^3.0.0

  
  simple_animations: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.3  

  http: 
  shared_preferences: ^2.0.6
  path_provider:
  provider: ^6.0.2
  sms_autofill: ^2.0.0 
  permission_handler: ^9.2.0
  dots_indicator: ^2.1.0
  webview_flutter: ^3.0.4
  get:
  get_storage:
  flutter_svg:
  firebase_core: "^1.5.0"
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.3.3
  firebase_auth: ^3.1.0
  firebase_storage: 
  cloud_firestore:  
  share: ^2.0.4
  image_picker: 
  image_cropper: 
  cached_network_image: ^3.1.0
  google_fonts: 

  

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true



  assets:
    - assets/

   




  fonts:
    - family: poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 500
        - asset: fonts/Poppins-Black.ttf
          weight: 700

    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
          weight: 100
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 500
        - asset: fonts/RobotoCondensed-Italic.ttf

    - family: Neoneon
      fonts:
        - asset: fonts/Neoneon-3zaD6.otf    
    - family: Neon
      fonts:
        - asset: fonts/Odense_Neon.ttf   

    - family: KumarkhaliMJ
      fonts:
        - asset: fonts/KumarkhaliMJ-Bold.ttf   
         
      
        
  